language: ruby
rvm:
- 2.4.4
deploy:
  run: "rake db:migrate"
  provider: heroku
  api_key:
    secure: Y/yW1uqzyuBvi+k+zwDPwG96Fjj0hyCybNwmBm2367kdiE9OKz2yBtlIi6NQXpeqA1ZC3SptS0t1ikhP10fhdLhXPJsD0O2NuPkkiO3aHcGvP95j8NQU+j0Io9xugwhtyqRlcC0ybFkgsIT8SuIWCpGHQcv0L9R4LkEds7wcdoteo5pIoGN/vmL6l0SRIofr08LyxualuzjcVgHuyeR79/HzHaEBc/QY5GiRBWcBgmaK3LMEKO7pLIG/OwZtGqfkmuc9vNQCIkej/nDkGrmDUmVybI8TWkr+wZx8tqkRiDu61CAfw7TLrBxUAcYJLIhza5SVzVKJ+AYAZU0NVLekaXPgrZDM4ztHRHOd3v3hC5rEO+xEvbfrS3h1+sWLpAD+RnARc5DsScWLOfri9CfkTetcIymIFQ/sDLeQePQDYIIuAwLBxAe9RFv+bvCnZ4b0zIo27A15+Zf4FT7SpoU5nsWvT1DMyhfF3bgEgbyNQo1XC1zq1iadeXWvg2T4xPdyHBtFUAfNNnLV5Bi6YstzZ4zi3GLDX3luN9tnxAxNH6VxK5/+4ChxrzUE15KHCXGHrnwGZx3l2gaH4kyw02cC7jxw8qvFRm2Y+ah1mM/WgsykxSI3aOFUHMms+rZcWXiiMFBk87GZZ5eagrl/3NbI2tGo558+3cfMcdJOI3lqoK0=
  app: pizzaschensy
  on:
    repo: chensy317/pizzas3
